spring:
  jpa:
    show-sql: true
  datasource:
    hikari:
      max-pool-size: 10
      transaction-isolation: TRANSACTION_REPEATABLE_READ
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5431/test_database
    username: postgres
  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.xml
  kafka:
    bootstrap-servers: localhost:29092
    speaker-like-topic: speakerLikeTopic
    connection-type: